name: pixaero
description: A new Flutter project.

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:

  bloc: ^8.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.0.4
  google_fonts: ^2.3.1
  intl: ^0.17.0
  json_annotation: ^4.4.0
  news_repository: 
    path: packages/news_repository
  url_launcher: ^6.0.20

dev_dependencies:
  json_serializable: ^6.1.4
  very_good_analysis: ^2.4.0


  



flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/


