name: news_repository
description: A Dart Repository which manages the news domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  news_api:
    path: ../news_api
    
dev_dependencies:
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  very_good_analysis: ^2.4.0
