name: news_api
description: A Dart API Client for the News API.
version: 1.0.0+1


environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.7
  coverage: ^1.1.0
  json_serializable: ^6.1.4
  mocktail: ^0.3.0
  test: ^1.20.1
  very_good_analysis: ^2.4.0

dependencies: 
  http: ^0.13.4 
  json_annotation: ^4.4.0
